package sem3Project;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kusha
 */

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;

public class TeachersPage extends javax.swing.JFrame {

    /**
     * Creates new form TeachersPage
     */
    
    /**
     *
     * @param sapID
     */
    
    private String sapID;
    private String myConnectionPass;
    
    public void initValues(String sapID, String myConnectionPass) {
        this.sapID = sapID;
        this.myConnectionPass = myConnectionPass;
    }
    
    Connection conn;
    PreparedStatement obj;
    PreparedStatement obj2;
    
    public TeachersPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attnd_flag = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        addCourseButton = new javax.swing.JButton();
        courseTeacherSAPIDTxtFeild = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        courseNameTxtFeild = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        courseNoTxtFeild = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        giveAttndStudentcourseNoTxtFeild = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentSAPIDTxtFeild = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        giveAttndStudentButton = new javax.swing.JButton();
        presentButton = new javax.swing.JRadioButton();
        absentButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        addCourseButton.setBackground(new java.awt.Color(30, 144, 255));
        addCourseButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        addCourseButton.setForeground(new java.awt.Color(255, 255, 255));
        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Teacher SAPID");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course Name");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Course No.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(courseNameTxtFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(courseTeacherSAPIDTxtFeild))
                            .addComponent(courseNoTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseNoTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseNameTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseTeacherSAPIDTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Add Course", jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        giveAttndStudentcourseNoTxtFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveAttndStudentcourseNoTxtFeildActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course No.");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student SAP ID");

        giveAttndStudentButton.setBackground(new java.awt.Color(30, 144, 255));
        giveAttndStudentButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        giveAttndStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        giveAttndStudentButton.setText("Give Attendance");
        giveAttndStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveAttndStudentButtonActionPerformed(evt);
            }
        });

        attnd_flag.add(presentButton);
        presentButton.setForeground(new java.awt.Color(255, 255, 255));
        presentButton.setText("Present");

        attnd_flag.add(absentButton);
        absentButton.setForeground(new java.awt.Color(255, 255, 255));
        absentButton.setText("Absent");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*For today");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(studentSAPIDTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(giveAttndStudentcourseNoTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(presentButton)
                            .addGap(52, 52, 52)
                            .addComponent(absentButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(87, 87, 87)
                            .addComponent(giveAttndStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giveAttndStudentcourseNoTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentSAPIDTxtFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presentButton)
                    .addComponent(absentButton))
                .addGap(40, 40, 40)
                .addComponent(giveAttndStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Give Attendance", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        String courseNo = this.courseNoTxtFeild.getText();
        String courseName = this.courseNameTxtFeild.getText();
        String courseTeacherSAPID = this.courseTeacherSAPIDTxtFeild.getText();
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sem_3_proj?user=kushal&password=" + myConnectionPass);
            
            obj = conn.prepareStatement("INSERT INTO courses(cno, course_name, teachers_id) VALUES(?, ?, (SELECT teachers_id FROM teachers WHERE sapid like ?))");
            
            obj.setString(1, courseNo);
            obj.setString(2, courseName);
            obj.setString(3, courseTeacherSAPID);
            
            obj.executeUpdate();
            
            obj2 = conn.prepareStatement("CREATE TABLE course_" + courseNo + " (" +
                                                " lecture_date DATE, " +
                                                " student_sapID VARCHAR(11),"+
                                                " attnd_flag VARCHAR(1) NOT NULL,"+
                                                " FOREIGN KEY(student_sapID) REFERENCES students(sapid)"+
                                           " )"
                                         );
            
            obj2.executeUpdate();
            
        } catch(SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void giveAttndStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveAttndStudentButtonActionPerformed
        // TODO add your handling code here:
        String courseNo = giveAttndStudentcourseNoTxtFeild.getText();
        String sapID = studentSAPIDTxtFeild.getText();
        LocalDate todaysDate = LocalDate.now();
        
        char attnd;
        if(presentButton.isSelected()) {
            System.out.println("Present");
            attnd = 'P';
        }
        else if(absentButton.isSelected()) {
            System.out.println("Absent");
            attnd = 'A';
        }
        else {
            attnd = '\0';
        }
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/sem_3_proj?user=kushal&password=" + myConnectionPass);
            
            obj = conn.prepareStatement("INSERT INTO course_" + courseNo + " VALUES(?, ?, ?)");
            
            obj.setString(1, todaysDate.toString());
            obj.setString(2, sapID);
            obj.setString(3, String.valueOf(attnd));
            
            obj.executeUpdate();
            
        } catch(SQLException e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_giveAttndStudentButtonActionPerformed

    private void giveAttndStudentcourseNoTxtFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveAttndStudentcourseNoTxtFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giveAttndStudentcourseNoTxtFeildActionPerformed

    
    private void addCourseButtonFocusGained(java.awt.event.FocusEvent evt) {
        addCourseButton.setBackground(Color.red);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TeachersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton absentButton;
    private javax.swing.JButton addCourseButton;
    private javax.swing.ButtonGroup attnd_flag;
    private javax.swing.JTextField courseNameTxtFeild;
    private javax.swing.JTextField courseNoTxtFeild;
    private javax.swing.JTextField courseTeacherSAPIDTxtFeild;
    private javax.swing.JButton giveAttndStudentButton;
    private javax.swing.JTextField giveAttndStudentcourseNoTxtFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton presentButton;
    private javax.swing.JTextField studentSAPIDTxtFeild;
    // End of variables declaration//GEN-END:variables
}
